/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package tree.fizz.buzz;

import org.checkerframework.checker.units.qual.A;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    App main=new App();
    @Test void testFizzBuzz() {
        k_tree <Integer>tree=new k_tree();
        tree.root=new node(1);
        tree.root.leftNode=new node(15);
        tree.root.leftNode.rightNode=new node(5);
        tree.root.rightNode=new node(3);
        k_tree sample_tree=main.fizzBuzzTree(tree);
        assertEquals("1",sample_tree.root.getValue());
        assertEquals("Fizz",sample_tree.root.rightNode.getValue());
        assertEquals("FizzBuzz",sample_tree.root.leftNode.getValue());
        assertEquals("Buzz",sample_tree.root.leftNode.rightNode.getValue());


    }
}
