/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package graph.business.trip;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    App classUnderTest = new App();

    @Test void test2ValidPath() {
        graph g = new graph();
        g.addNode("A");
        g.addNode("B");
        g.addNode("C");
        g.addNode("D");
        g.addEdge("A", "B", 2);
        g.addEdge("B", "C", 4);
        g.addEdge("B", "D", 5);
        String []array={"A","B"};
        int actual=classUnderTest.busniess_trip(g,array);
        int expected=2;
        assertEquals(expected,actual);

    }
    @Test void test3ValidPath() {
        graph g = new graph();
        g.addNode("A");
        g.addNode("B");
        g.addNode("C");
        g.addNode("D");
        g.addEdge("A", "B", 2);
        g.addEdge("B", "C", 4);
        g.addEdge("B", "D", 5);
        String []array={"A","B","C"};
        int actual=classUnderTest.busniess_trip(g,array);
        int expected=6;
        assertEquals(expected,actual);

    }
    @Test void testAnother3ValidPath() {
        graph g = new graph();
        g.addNode("A");
        g.addNode("B");
        g.addNode("C");
        g.addNode("D");
        g.addEdge("A", "B", 2);
        g.addEdge("B", "C", 4);
        g.addEdge("B", "D", 5);
        String []array={"A","B","D"};
        int actual=classUnderTest.busniess_trip(g,array);
        int expected=7;
        assertEquals(expected,actual);

    }
    @Test void testUnValidPath() {
        graph g = new graph();
        g.addNode("A");
        g.addNode("B");
        g.addNode("C");
        g.addNode("D");
        g.addEdge("A", "B", 2);
        g.addEdge("B", "C", 4);
        g.addEdge("B", "D", 5);
        String []array={"A","D"};
        int actual=classUnderTest.busniess_trip(g,array);
        int expected=0; // 0 mean null
        assertEquals(expected,actual);

    }
}
