/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quickSort;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    App classUnderTest = new App();
//[8,4,23,42,16,15]
    @Test void testFirstArray() {
        int []array={8,4,23,42,16,15};
        int []newarray=classUnderTest.quickSort(array,0,array.length-1);
        String actual="";
        for(int j=0;j<newarray.length;j++){
            if(j!=newarray.length-1){
             actual=actual+newarray[j]+",";
            }else{
                 actual=actual+newarray[j]+"";
            }

        }
        String expected = "4,8,15,16,23,42";
        assertEquals(expected,actual);
    }
//    [20,18,12,8,5,-2]
    @Test void testSecondArray() {
        int []array={20,18,12,8,5,-2};
        int []newarray=classUnderTest.quickSort(array,0,array.length-1);
        String actual="";
        for(int j=0;j<newarray.length;j++){
            if(j!=newarray.length-1){
                actual=actual+newarray[j]+",";
            }else{
                actual=actual+newarray[j]+"";
            }

        }
        String expected = "-2,5,8,12,18,20";
        assertEquals(expected,actual);
    }
    //    [5,12,7,5,5,7]
    @Test void testThirdArray() {
        int []array={5,12,7,5,5,7};
        int []newarray=classUnderTest.quickSort(array,0,array.length-1);
        String actual="";
        for(int j=0;j<newarray.length;j++){
            if(j!=newarray.length-1){
                actual=actual+newarray[j]+",";
            }else{
                actual=actual+newarray[j]+"";
            }

        }
        String expected = "5,5,5,7,7,12";
        assertEquals(expected,actual);
    }
//    [2,3,5,7,13,11]
    @Test void testFourthArray() {
        int []array={2,3,5,7,13,11};
        int []newarray=classUnderTest.quickSort(array,0,array.length-1);
        String actual="";
        for(int j=0;j<newarray.length;j++){
            if(j!=newarray.length-1){
                actual=actual+newarray[j]+",";
            }else{
                actual=actual+newarray[j]+"";
            }

        }
        String expected = "2,3,5,7,11,13";
        assertEquals(expected,actual);
    }

}
