/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package stack.queue.brackets;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    App sample = new App();
    @Test void testWithSimpleBrakets() {
        assertTrue( sample.validate_brackets("[]"));
        assertTrue( sample.validate_brackets("()"));
        assertTrue( sample.validate_brackets("{}"));

    }
    @Test void testWithBraketsWithTextBetween() {
        assertTrue( sample.validate_brackets("[hello]"));
        assertTrue( sample.validate_brackets("(test)"));
        assertTrue( sample.validate_brackets("{wassup}"));

    }
    @Test void testWithmoreThanOneBraketInText() {
        assertTrue( sample.validate_brackets("[]()"));
        assertTrue( sample.validate_brackets("()[]"));
        assertTrue( sample.validate_brackets("{}[]()"));

    }
    @Test void testWithNonValidBrakets() {
        assertFalse( sample.validate_brackets("[dfsdgs)"));
        assertFalse( sample.validate_brackets("(dfs]{d}"));
        assertFalse( sample.validate_brackets("{ee}sdfs[sd)"));

    }
}
