/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linked.list.insertions;

import org.junit.jupiter.api.Test;

import javax.print.attribute.HashPrintJobAttributeSet;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    LinkedList sample=new LinkedList();

    @Test void addNodeToEndOfList() {
        int []array;
        assertFalse(sample.includes(1));
        int value1=1,value2=3,value3=5,value4=4,value5=2,value6=6,value7=0;
     sample.append(value1); array= new int[]{value1};
     sample.append(value2); array= new int[]{value1, value2};
     sample.append(value3); array= new int[]{value1, value2,value3};
     sample.insert_Before(value3,value4); array= new int[]{value1, value2,value4,value3};
     sample.insert_after(value1,value5);  array= new int[]{value1,value5, value2,value4,value3};
     sample.append(value6); array= new int[]{value1,value5, value2,value4,value3,value6};
     sample.insert_Before(value1,value7); array= new int[]{value7,value1,value5, value2,value4,value3,value6};

        String result="[";
        for(int i=0;i<array.length;i++){
            if(!(i==array.length-1)) {
                result = result + array[i] + ", ";
            }
            else {
                result = result + array[i] + "]";
            }
        }
        sample.toString();
        assertEquals(sample.linked_list_current_values.toString(),result);



    }
}
