/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linked.list.zip;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    App classUnderTest = new App();
    LinkedList firstSample=new LinkedList();
    LinkedList secondSample=new LinkedList();
    @Test void TestExpectedOutcomeForZipListMethod() {
        firstSample.insert(1);
        firstSample.insert(2);
        firstSample.insert(3);
        secondSample.insert(10);
        secondSample.insert(20);
        secondSample.insert(30);
        classUnderTest.zipLists(firstSample,secondSample);
        String excepted="{1} -> {10} -> {2} -> {20} -> {3} -> {30} -> NULL";
        assertEquals(excepted,firstSample.toString());
    }
    @Test void TestExpectedFailureForZipListMethod() {
        firstSample.insert(1);
        firstSample.insert(2);
        firstSample.insert(3);
        secondSample.insert(10);
        secondSample.insert(20);
        secondSample.insert(30);
        secondSample.insert(40);
        classUnderTest.zipLists(firstSample, secondSample);
        String excepted="{1} -> {10} -> {2} -> {20} -> {3} -> {30} -> {40} -> NULL";
        assertNotEquals(excepted,firstSample.toString());

    }
    @Test void TestEdgeCasesForZipListMethod() {
        firstSample.insert(1);
        firstSample.insert(2);
        firstSample.insert(3);
        secondSample.insert(10);
        secondSample.insert(20);
        secondSample.insert('3');
        classUnderTest.zipLists(firstSample, secondSample);
        String excepted="{1} -> {10} -> {2} -> {20} -> {3} -> {3} -> NULL";
        assertNotEquals(excepted,firstSample.toString());

    }
}
