/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hashmap.left.join;

import org.junit.jupiter.api.Test;

import java.util.Arrays;
import java.util.HashMap;

import static hashmap.left.join.App.left_join;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {

    @Test void TestIfTheResultContainsTheUnvalid() {
        HashMap<String, String> first = new HashMap();
        HashMap<String, String> second = new HashMap();

        first.put("diligent","employed");
        first.put("fond","enamored");
        first.put("guide","usher");
        first.put("outfit","garb");

        second.put("diligent","idle");
        second.put("fond","averse");
        second.put("guide","follow");
        second.put("flow","jam");



        assertFalse(Arrays.deepToString(left_join(first,second).toArray()).contains("flow"));
        assertFalse(Arrays.deepToString(left_join(first,second).toArray()).contains("jam"));


    }

    @Test void TestIfTheResultContainsTheValid() {
        HashMap<String, String> first = new HashMap();
        HashMap<String, String> second = new HashMap();

        first.put("diligent","employed");
        first.put("fond","enamored");
        first.put("guide","usher");
        first.put("outfit","garb");

        second.put("diligent","idle");
        second.put("fond","averse");
        second.put("guide","follow");
        second.put("flow","jam");

        assertTrue(Arrays.deepToString(left_join(first,second).toArray()).contains("diligent"));
        assertTrue(Arrays.deepToString(left_join(first,second).toArray()).contains("enamored"));

        assertTrue(Arrays.deepToString(left_join(first,second).toArray()).contains("outfit"));
        assertTrue(Arrays.deepToString(left_join(first,second).toArray()).contains("idle"));
    }

    @Test void TestAnotherInputsValid() {
        HashMap<String, String> first = new HashMap();
        HashMap<String, String> second = new HashMap();

        first.put("hello","hi");
        first.put("me","I");
        first.put("they","people");
        first.put("nice","beatiful");

        second.put("hello","goodbye");
        second.put("me","u");
        second.put("they","I");
        second.put("nice","ugly");

        assertTrue(Arrays.deepToString(left_join(first,second).toArray()).contains("goodbye"));
        assertTrue(Arrays.deepToString(left_join(first,second).toArray()).contains("u"));

        assertTrue(Arrays.deepToString(left_join(first,second).toArray()).contains("beatiful"));
        assertTrue(Arrays.deepToString(left_join(first,second).toArray()).contains("hi"));
    }

}
