/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linked.list.kth;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

class MainTest {
    LinkedList sample=new LinkedList();
    @Test void K_IsGreaterThanLength() {
        sample.insert(5);
        sample.insert(6);
        sample.insert(7);
        sample.insert(8);
        sample.insert(9);
        sample.kth_from_end(11);
        assertTrue(sample.isThereException);

    }
    @Test void K_IsSameLength(){
        sample.insert(5);
        sample.insert(6);
        sample.insert(7);
        sample.insert(8);
        sample.insert(9);
        assertEquals(5,sample.kth_from_end(4));
        assertFalse(sample.isThereException);
    }
    @Test void K_IsNegative(){
        sample.insert(5);
        sample.insert(6);
        sample.insert(7);
        sample.insert(8);
        sample.insert(9);
        sample.kth_from_end(-5);
        assertTrue(sample.isThereException);
    }
    @Test void lengthIs1(){
        sample.insert(5);
        assertEquals(5,sample.kth_from_end(0));
        assertFalse(sample.isThereException);
    }
    @Test void K_InMiddle(){
        sample.insert(5);
        sample.insert(6);
        sample.insert(7);
        sample.insert(8);
        sample.insert(9);
        assertEquals(sample.kth_from_end(5/2),7);
        assertFalse(sample.isThereException);
    }
}
