/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hashtable;

import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.TestInstance;

import static org.junit.jupiter.api.Assertions.*;
@TestInstance(TestInstance.Lifecycle.PER_CLASS)
class AppTest {
    hashtable<String,Integer> h=new hashtable();

    @BeforeAll

      public  void init(){
        h.set("java",23);
        h.set("c++",45);
        h.set("c#",67);
        h.set("java",78);

    }


    @Test void getkey() {
        String expected="23";
        String actual=h.get("java");
        assertEquals(expected,actual);

    }


    @Test void checkAnValidKey() {
        String expected="null";
        String actual=h.get("python");
        assertEquals(expected,actual);

    }


    @Test void returnListUniqueKey() {
        String expected="BUCKET 4=[c#:67]\n" +
                "BUCKET 5=[c++:45]\n" +
                "BUCKET 8=[]\n";
        String actual=h.AllUniqueKeys();
        assertEquals(expected,actual);
    }
    @Test void hashTheKey() {
        int expected=3329;
        int actual=h.hashCode("hi");
        assertEquals(expected,actual);
    }

}
