/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package graph.breadth.first;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void firstTestBeginFromB() {
        graph sample=new graph();
        sample.addNode("A");
        sample.addNode("B");
        sample.addNode("C");
        sample.addNode("D");
        sample.addEdge("A","D");
        sample.addEdge("A","C");
        sample.addEdge("C","B");
        sample.addEdge("D","B");
        String actual=sample.breadth_first(new Vertex("B")).toString();
        String expected="[Vertex{data='B'}, Vertex{data='C'}, Vertex{data='D'}, Vertex{data='A'}]";
        assertEquals(expected, actual);
    }
    @Test void secondTestBeginFromA() {
        graph sample=new graph();
        sample.addNode("A");
        sample.addNode("B");
        sample.addNode("C");
        sample.addNode("D");
        sample.addEdge("A","D");
        sample.addEdge("A","C");
        sample.addEdge("C","B");
        sample.addEdge("D","B");
        String actual=sample.breadth_first(new Vertex("A")).toString();
        String expected="[Vertex{data='A'}, Vertex{data='D'}, Vertex{data='C'}, Vertex{data='B'}]";
        assertEquals(expected, actual);
    }
    @Test void thirdTestBeginFromC() {
        graph sample=new graph();
        sample.addNode("A");
        sample.addNode("B");
        sample.addNode("C");
        sample.addNode("D");
        sample.addEdge("A","D");
        sample.addEdge("A","C");
        sample.addEdge("C","B");
        sample.addEdge("D","B");
        String actual=sample.breadth_first(new Vertex("C")).toString();
        String expected="[Vertex{data='C'}, Vertex{data='A'}, Vertex{data='B'}, Vertex{data='D'}]";
        assertEquals(expected, actual);
    }
}
