/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package stack.queue.brackets;

public class App {


    public static void main(String[] args) {


    }
    public static boolean validate_brackets(String text){
   boolean conditionWillStopTheProgram=false;
   boolean result=false;
   String type="";
   char otherBraket='!';
   boolean braket=false;
   for(int i=0;i<text.length();i++){
       if(conditionWillStopTheProgram){
           break;
       }
       if(text.charAt(i)=='{') {
           otherBraket='}';
           result=false;
           braket=true;
       }
       else if(text.charAt(i)=='['){
           otherBraket=']';
           result=false;
           braket=true;
       }
       else if(text.charAt(i)=='('){
           otherBraket=')';
           result=false;
           braket=true;
       }
       if(braket){
           i++;
           while(i!=text.length()){
               if(text.charAt(i)=='}'||text.charAt(i)==')'||text.charAt(i)==']'){
                   if(text.charAt(i)==otherBraket){
                       result=true;
                       braket=false;
                       break;
                   }
                   else{
                       conditionWillStopTheProgram=true;
                       result=false;
                       break;
                   }

               }
               if(i+1==text.length()){
                   result=false;
                   break;
               }
               i++;
           }
       }

       if(i+1==text.length()&&braket){
           result= false;
       }
   }
        return result;
    }

}
