/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linked.list;

public class App {

    public static void main(String[] args) {
LinkedList f=new LinkedList();
f.insert(5);
f.insert(6);
f.insert(7);
System.out.println(f.includes(6));
System.out.println(f.toString());
    }
}
