/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package stack.queue.animal.shelter;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void AnimalShelterTest() {
        AnimalShelter sample=new AnimalShelter();
        sample.enqueue(new animal("cat"));
        String exceptionForValidInput="cat";
        String actualForValidInput=sample.rear.type;
        assertEquals(exceptionForValidInput,actualForValidInput);

        sample.enqueue(new animal("monkey"));
        String exceptionForNotValidInput="cat";
        String actualForNotValidInput=sample.rear.type;
        assertEquals(exceptionForNotValidInput,actualForNotValidInput);

        String exceptionForDequeueValied="cat";
        String actualForDequeueValied=sample.dequeue("cat");
        assertEquals(exceptionForDequeueValied,actualForDequeueValied);

        String exceptionForDequeueNotValied=null;
        String actualForDequeuenotValied=sample.dequeue("monkey");
        assertEquals(exceptionForDequeueNotValied,actualForDequeuenotValied);



    }
}
