/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package stack.queue.animal.shelter;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void AnimalShelterTest() {
        AnimalShelter sample=new AnimalShelter();
        sample.enqueue(new cat());
        String exceptionForValidInput="cat";
        String actualForValidInput=sample.rear.value;
        assertEquals(exceptionForValidInput,actualForValidInput);

        sample.enqueue(new dog());
        String exceptionForNotValidInput="dog";
        String actualForNotValidInput=sample.front.value;
        assertEquals(exceptionForNotValidInput,actualForNotValidInput);

        String exceptionForDequeueValied="cat";
        String actualForDequeueValied=sample.dequeue("cat");
        assertEquals(exceptionForDequeueValied,actualForDequeueValied);

        String exceptionForDequeueNotValied="dog";
        String actualForDequeuenotValied=sample.dequeue("dog");
        assertEquals(exceptionForDequeueNotValied,actualForDequeuenotValied);



    }
}
